### ISSUE TITLE
Support For NSF Input

### ISSUE THREAD

**Issue by ghost** [libertyernie/LoopingAudioConverter#10]
What is a feasibility of adding support for converting from NSF (NES) format? 

I just spent a few hours researching how to convert NSFs and the app workflows seem pretty awful. The main issue is that NSFs are just one file that has all of the games tracks.

I found a random site with a load of NSFs and M3U files that show when each song ends. Would this be useful? I also found a commandline converter for NSFs. NSF2WAV (http://nezplug.sourceforge.net/)

Are you planning on adding support for NSFs?

**Comment by libertyernie** [comment]
The hard thing about .nsf is that there's more than one song in the file. Looping Audio Converter at the moment assumes 1 file = 1 song.

I'll look into NSF2WAV and the M3U files though. Maybe it would be possible to make something work.

**Comment by davidpgil** [comment]
Yeah, thats the same issue with SPC and GYM files too. Thanks. If I come up with something I will let you know.

**Comment by libertyernie** [comment]
You might want to try this site. It's got NES music in VGM format.
http://vgmrips.net/packs/system/nintendo/nintendo-entertainment-system

**Comment by davidpgil** [comment]
Sure. I know of this site. However, how did these guys get there VGMs? Would be cool to at least find a NSF native file and convert it to a VGM.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
