### ISSUE TITLE
add .bars support

### ISSUE THREAD

**Issue by castdrian** [libertyernie/LoopingAudioConverter#12]

**Comment by libertyernie** [comment]
I expect .bars would have a similar issue as nus3bank, in that each file has more than one song. Looping Audio Converter doesn't have a way to pick one.
Is there software that can extract or replace songs from a .bars file in some other format (like WAV or DSP)?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
