### ISSUE TITLE
[Feature Request] Add command line conversion

### ISSUE THREAD

**Issue by VideogameScrapbook** [libertyernie/LoopingAudioConverter#18]
It would be great to be able to use Looping Audio Converter as part of a batch without learning how to use several different tools. As a starting point, Looping Audio Converter could just support one parameter (which would be the input file) and it would default simply to converting to brstm format. This simple design would also allow dragging a single file onto the exe for direct conversion to the same filename but with the brstm file extension.

After this first iteration of fulfilling this request, then other parameters/command line options could be added as desired.

On a related note, at this time, I'm not aware of a command line exe that will convert directly from a wav with smpl chunk to brstm format. Is there a solution for the time being already available?

**Comment by libertyernie** [comment]
VGAudio is the library I use to handle BRSTM. Have you tried VGAudioCli? It supports BRSTM and WAV input and output, and it looks like it can both read and write smpl chunks.

https://github.com/Thealexbarney/VGAudio

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
