### ISSUE TITLE
Add little endian BFSTM and BRWAV support

### ISSUE THREAD

**Issue by khang06** [libertyernie/LoopingAudioConverter#19]
For Nintendo Switch.

**Comment by fancymelonub** [comment]
Might be already supported by vgmstream, if so then adding support for those will probably be easy.

**Comment by libertyernie** [comment]
If vgmstream supports them, they might already work as input formats.

For output, I think I'd have to wait for VGAudio to support them.

**Comment by libertyernie** [comment]
I just added little-endian BFSTM. VGAudio can't create BRWAV files though.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
