### ISSUE TITLE
Issue with .wv6 files

### ISSUE THREAD

**Issue by clorofolle** [libertyernie/LoopingAudioConverter#24]
hello! I had to convert 800+ wv6 audio files from an old pc game. At first I downloaded the zip from the master branch - Vgstream supports the format, and I had no issue converting a few of them into wav by dragging and dropping each one into test.exe.
This was of course very tedious so I downloaded the latest (2.2.1) windows release to open the user interface, but it keeps refusing to open the files - probably because it doesn't recognize the format. And in fact if I try to drag and drop the wv6 files in the test.exe found in the 2.2.1 release, it won't convert them.
By replacing the whole vgstream folder with the one I found in the master release, things... sort of work? But not quite.
Whenever I try to convert from the user interface, I still get the "could not read X" error message, but when I look in the audios' folder, I do actually find a converted wav file! So test.exe actually runs. I still cannot control the output format, but if I just dismiss an error message for each sound file, I can "convert" 128 tracks at a time (by modifying the number of simultaneous tasks) before LoopingAudioConverter.exe crashes.

**Comment by libertyernie** [comment]
Could you post a link to one of the wv6 files so I can try it?

In your case, I wonder if it might be easier to use Winamp with the vgmstream plugin and WAV output.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
