### ISSUE TITLE
"File already exists" not properly handled

### ISSUE THREAD

**Issue by ehx-v1** [libertyernie/LoopingAudioConverter#29]
When you try to convert to a file that already exists, it results in the generic "exe has stopped working". Maybe add proper handlers so an error prompt opens up instead?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
