### ISSUE TITLE
Progress indicator bar doesn't work correctly

### ISSUE THREAD

**Issue by rawr51919** [libertyernie/LoopingAudioConverter#3]
The indicator bar doesn't show up when you go to convert a brstm into a looping wav. Can someone take a look into why it's not working as it should? This happens in the latest version.

**Comment by libertyernie** [comment]
Is this the bar for decoding the brstm, or for encoding the wav? Could you take a screenshot?

**Comment by coltongit** [comment]
There's only one there which does both.

**Comment by libertyernie** [comment]
Can you post a screenshot of what you are seeing?

**Comment by coltongit** [comment]
I see the name of the brstm flash briefly and then I don't see anything on the progress bar. It does finish though.

**Comment by libertyernie** [comment]
I don't think the progress bar for exporting WAV files has ever shown anything. How long does it take?

**Comment by coltongit** [comment]
Encoding the wav. Unfortunately, it goes by too quick for me to post a
screenshot.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
