### ISSUE TITLE
BCSTM output doesn't allow specific Sample Rate

### ISSUE THREAD

**Issue by sygemdev** [libertyernie/LoopingAudioConverter#34]
Specifically for MK7 music, that game requires that race music be 32728 Hz. When I try to output with this sample rate (using the 'New sample rate' feature, LAC instead outputs at 32000 Hz, rather than the sample rate I specified.

**Comment by MDHEXT** [comment]
The input file was probably less than 32728hz. on top of that, for mk7, files don't need to be 32728hz, they work fine at sample rates up to 48khz, because mk7's bcstm format is encoded in a special way that allows for the game to load music in while doing many other things. The bcsar file also has similar encoding specs.

**Comment by libertyernie** [comment]
This should be fixed in the new version (although I wouldn't recommend converting a file up to 32728 Hz if it's currently less than that, unless it doesn't work otherwise - it would just be wasted disk space)
