### ISSUE TITLE
feature request: VST effect support

### ISSUE THREAD

**Issue by MDHEXT** [libertyernie/LoopingAudioConverter#39]
I like to use VST effects in some projects, is there a way to add VST support?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
