### ISSUE TITLE
Feature request: support for "sf" formats.

### ISSUE THREAD

**Issue by MDHEXT** [libertyernie/LoopingAudioConverter#40]
I'd like to request the ability to convert from "sf" formats such as 2sf, ncsf, psf, etc to streamed formats. This isn't an easy feature to implement because "sf" formats are sequenced, not streamed so if you can, please try to implement this feature.

**Comment by libertyernie** [comment]
Do you know how to examine (say) a .ncsf file and determine where the loop point in the song is? If we can get that info, then we just need to find a program that can convert it to .wav. That's what I did to implement .vgm input support.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
