### ISSUE TITLE
Feature Request: Selecting certain channels for conversion

### ISSUE THREAD

**Issue by Tanookirby** [libertyernie/LoopingAudioConverter#41]
I came across this program the other day when looking to convert a few files. But I noticed the channel splitting options are limited. Would it be possible to add a feature that allows the user to choose whichever channels he or she wants for the converted file?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
