### ISSUE TITLE
odd numbered chunk sizes in WAV headers cause errors

### ISSUE THREAD

**Issue by Algorithmus** [libertyernie/LoopingAudioConverter#42]
I had this problem coming from rstmcpp, and I see that the c# version of it looks very similar. The problem on my end was that some chunk sizes in data or other types of chunk headers for metadata cause the reading to become misaligned, and the chunks are no longer correctly being read. There is probably some padding bytes after the chunk so that it aligns correctly, but I fixed it like this: https://gitlab.com/beelzy/rstmcpp/-/commit/36928e95bcdb477b9324bde38432df90d9c966b1#142fb1a31fbbc3dca44066cd354a542baf0e63dd_111_111

And some more background information about how this happens: https://github.com/mono/taglib-sharp/issues/101

I know there's not a whole lot of interest in rstmcpp on your end, but I also fixed a minor issue with 8 bit file conversion to 16 bit, which you can also see in my commit.

**Comment by libertyernie** [comment]
Thanks. Mind if I merge your rstmcpp master branch into mine here on github?

Also, it's been a while since I've looked at LoopingAudioConverte, but I think it now just uses the VGAudio library for RSTM encoding. But if I'm remembering wrong and there's a place I could apply this fix in this repository, just let me know :)

**Comment by Algorithmus** [comment]
Sure, you can merge my master branch into yours.
The fix is for the part where it's reading the wav files. If you're not using looping audio converter for that, then I suppose you won't need it.
