### ISSUE TITLE
Feature request: Criware AAX encoding/decoding support

### ISSUE THREAD

**Issue by BestestHD** [libertyernie/LoopingAudioConverter#43]
Current options for AAX encoding are very limited. I believe it's just ADX with a different header? It supports segments. My current dilemma is making an AAX file with 1 segment loop from start-to-end; this isn't possible with current tools.

**Comment by libertyernie** [comment]
Looping Audio Converter depends on the VGAudio library currently for ADX encoding. Do you have a link to documentation that shows how to convert ADX to AAX or vice versa?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
