### ISSUE TITLE
Limit CPU usage of the program.

### ISSUE THREAD

**Issue by DrFe4r** [libertyernie/LoopingAudioConverter#44]
Not an issue but more a feature, would there be a way to limit how much CPU is being used by the program even at the cost of time? For example it only uses 50% of the CPU at any one time, instead of the default where it uses as much CPU as possible.

**Comment by libertyernie** [comment]
I'm not sure if you can do this in .NET, but there's probably a way to set the CPU priority to a lower value for processes that get launched (like sox.exe, etc.)

Not quite sure how to do it for the main process itself but I bet that's possible somehow too.

Alternatively, it might be possible to go in Windows Task Manager and change the priority of whatever process is taking up the CPU, so that other processes take priority.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
