### ISSUE TITLE
BCSTMs from LoopingAudioConverter do not work in-game in some cases

### ISSUE THREAD

**Issue by CuberHax** [libertyernie/LoopingAudioConverter#45]
Whenever I convert any format to BCSTM format, the BCSTM doesn't work with Mario Kart 7. When the BCSTM is supposed to play, no music plays. I suspect that BCSTMs from LoopingAudioConverter will also not work for some games other than Mario Kart 7. I want to use LoopingAudioConverter to efficiently amplify the volume of multiple custom BCSTMs at a time, but this issue makes this not possible. Yes, I have tried converting one file at a time, and it does not change anything.

**Comment by libertyernie** [comment]
Do you have a link to documentation about Mario Kart 7's format, or a program that can create BCSTMs that Mario Kart 7 can play?

**Comment by CuberHax** [comment]
I know a program that I think can create the proper BCSTMs (if memory serves correctly), and it's open source too.

https://github.com/soopercool101/BrawlCrate

**Comment by libertyernie** [comment]
If you have time, try out the new version, it includes the BrawlCrate encoder.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
