### ISSUE TITLE
VGZ conversion crashes 

### ISSUE THREAD

**Issue by soltype** [libertyernie/LoopingAudioConverter#46]
Can't seem to get all my VGZ files to convert.It happens with wav, flac, mp3, etc.It usually starts of fine then locks up after a couple of files.Anybody else running into this issue?

**Comment by libertyernie** [comment]
See if it works better in version 3.0, a couple things have been changed in that release.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
