### ISSUE TITLE
Possible Addition of SPC support-

### ISSUE THREAD

**Issue by Bonboon229** [libertyernie/LoopingAudioConverter#47]
Could it be possible to program in SPC support for snes music files? I reckon it could be doable with SPCPlay, sorta like how you integrated VGM support.

**Comment by libertyernie** [comment]
I'm not sure SPC files generally have loop information - I think the only required thing is that you tell the player how long to play for, and that's usually two loops plus a fade out: http://www.vgmpf.com/Wiki/index.php?title=SPC#Technical

That being said, I can't find out what the actual format is, so I could be wrong.

VGM files are a bit higher-level than SPC, I think, because they need to support audio for different combinations of hardware.

**Comment by Bonboon229** [comment]
Alright, thanks for getting back to me on that. Either way, hopefully looking forward to where you go with this tool.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
