### ISSUE TITLE
Request: Regarding loop processing.

### ISSUE THREAD

**Issue by SysVR** [libertyernie/LoopingAudioConverter#49]
$It is a request for additional options.

Encode only if loop chunks are present,
Files that did not have a loop are kept in the file list.

$2Pass Fade Out
2Pass  Fade-out time [Num]

make a natural fade-out by making 2 passes.
For example, if the first pass is 10 seconds and the second pass is 2.5 seconds,
Fade out for 7 seconds, then 3 seconds from behind
Fade out.

ex. - is fadeout
1Pass [----------]
2Pass [_______---]

$Silence section after fading out
Currently, there is no silence after fading out and it leads to the next song, so it is a little unnatural compared to a general CD.
Silence after Fade-out time [Num]

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
