### ISSUE TITLE
Problem with Wii game music

### ISSUE THREAD

**Issue by malekairmaroc7** [libertyernie/LoopingAudioConverter#5]
I made a music for my game. I use LoopingAudioConverter. But the game music stops after 1 minute. What should I do?

**Comment by libertyernie** [comment]
Did you try setting "For non-looping files" to "force start-to-end loop"? Also, what game is it for?

**Comment by malek78i** [comment]
It is for my own game. Super Mario Bros. Wii

**Comment by libertyernie** [comment]
Does that "force start-to-end loop" setting do anything to help?

**Comment by malek78i** [comment]
I do it later. I will say now, maybe.

Am Dienstag, 18. April 2017 schrieb libertyernie :

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
