### ISSUE TITLE
--auto Command Line Option Hangs

### ISSUE THREAD

**Issue by ilazoja** [libertyernie/LoopingAudioConverter#50]
I tried using the --auto command line option to convert an mp3 to brstm from the command line but the application seems to hang, I don't get this issue when running the program normally. Tested on Windows 10.

**Comment by ilazoja** [comment]
After some poking around, it seems related to reading and writing files, for some reason doing it asynchronously when running --auto from the command line causes the program to hang, but it works if you read and write them synchronously

**Comment by libertyernie** [comment]
I wonder if making them asynchronous and parallel is more trouble than it's worth. I might just change the app to do files one at a time (although it probably won't be in the next release).

In the meantime, I changed `--auto` to actually show the UI and then click the button for you - hopefully that works.

Mind if I pull in your other change with the input folder field?

**Comment by ilazoja** [comment]
Ah sounds good! I'll give that a try

And yep feel free too!

**Comment by libertyernie** [comment]
A new version's out, if you have time you can try it & see if that works better for you.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
