### ISSUE TITLE
wont let me start the converting process 

### ISSUE THREAD

**Issue by Ne0nDragon** [libertyernie/LoopingAudioConverter#51]
when I try to start converting the audio it tells me that it cant read the mp3 audio. plz help

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
