### ISSUE TITLE
Request Input Option .BFGRP

### ISSUE THREAD

**Issue by thor221** [libertyernie/LoopingAudioConverter#52]
I'm attempting to get all the sounds out of Metroid Dread and some of the files have the extension ".BFGRP" and LAC cannot recognize it.

**Comment by libertyernie** [comment]
Do you have a link to documentation on the .bfgrp files or any programs that can read or write it?

**Comment by thor221** [comment]
I do.  This is a tool that can read and play the .bfgrp files and edit them.
https://github.com/Gota7/Citric-Composer

The author also has documentation on the file format here.
https://gota7.github.io/Citric-Composer/

The tool has a method to export them as .wav but it only allows for one file to be exported at a time as it was primarily designed for editing and not dumping.

If you need/want .bfgrp files for reference I can supply some to you.

**Comment by libertyernie** [comment]
So .bfgrp files can contain more than one audio track, correct? LoopingAudioConverter doesn't support extracting multiple audio tracks from one file yet, but it's something that might be added eventually.

**Comment by thor221** [comment]
I don't know if they can contain multiple tracks or not. From my analysis of the files that I have they only have one track.

When I said "multiple files" I was talking about batch file exporting which LoopingAudioConverter already supports.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
