### ISSUE TITLE
[Feature Request] AAC as Output

### ISSUE THREAD

**Issue by AngelSora** [libertyernie/LoopingAudioConverter#6]
I wanted to Change the Music of Pokemon X and Y. 3DS games usually use BCSTM, but this one use AAC instead. I just want to convert BCSTMs to AACs format.

**Comment by libertyernie** [comment]
Can you try this version and see if it works? https://github.com/libertyernie/LoopingAudioConverter/releases/tag/v1.4.0rc1

**Comment by AngelSora** [comment]
Sorry i was out way too long, I'm testing it right now !

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
