### ISSUE TITLE
[Request] Option to define final duration instead of number of loops

### ISSUE THREAD

**Issue by Voxybuns** [libertyernie/LoopingAudioConverter#65]
Hello,
I'd like to request an additional option regarding the handling of loops.

I want to export extended rips of a game's OST, but only having the option to select a number of loops makes it tricky to export a file with the intended length, especially when the loop points wildly vary between tracks. I think it'd be great to have a second option where you can input a target length (say 15 or 30 minutes), and let the program figure out how many loops that would equate to.

**Comment by Voxybuns** [comment]
Hi, just wanted to know if there was any update on this! ^^

**Comment by libertyernie** [comment]
I haven't built a new version of the app (yet), but it should be in the main source tree - if you get Visual Studio 2022 Community installed and compile this project, it would probably work. I don't know when I'll get around to making the build so that might be faster :)

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
