### ISSUE TITLE
Any plans to support GBA/NDS/N64 music?

### ISSUE THREAD

**Issue by ghost** [libertyernie/LoopingAudioConverter#66]
Would honestly be nice if these were supported: I'm actually using this tool rn to make an SMBX2 episode and it would be REALLY nice for me not to manually loop music that's from the N64-NDS era. Thanks!

**Comment by libertyernie** [comment]
The tricky thing about most of these formats (other than VGM) is that the files don't tell the player how long a loop takes - the player just emulates the sound chips in the console for however long you tell it to.

It would be possible to specify an amount of time and have the song play for that long - a future version of Looping Audio Converter might have this feature - but as far as Looping Audio Converter is concerned, it wouldn't be a song with a loop, it'd just be a song with infinite length. At that point you could probably use Winamp and its .wav output to do much the same thing.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
