### ISSUE TITLE
Coverting Wavs with more than 2 channels crashes

### ISSUE THREAD

**Issue by Azula110** [libertyernie/LoopingAudioConverter#67]
When you try to use a wav file (or really any audio file) with more than 2 channels and select "put all channels in one file" the program hard crashes.

I've been trying to get around this issue for hours and no matter what I did to the wav file, it would not work

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
