### ISSUE TITLE
[Request] Export segment AFTER loop

### ISSUE THREAD

**Issue by KobobKC** [libertyernie/LoopingAudioConverter#68]
Recently I found out that some tracks can have a segment after the looped part, and that part gets lost if you only export "segment before loop" and "loop segment". I'd like to go back through a lot of files and see if they have parts after the loop but the only way to do that (that I know of) is to check all three boxes to export the whole song, the beginning, and the loop, then line them up in Audacity and see if the "whole song" is longer than the beginning and looped parts combined. However that would take forever to do manually, so it would be nice if there was a feature to export the end.

**Comment by libertyernie** [comment]
I wonder if LoopingAudioConverter is making some assumptions that the loop end is also the file end - fixing that might be tricky to do, but I can see how it would be helpful. What type are the input files?

**Comment by KobobKC** [comment]
[1006139530.zip](https://github.com/libertyernie/LoopingAudioConverter/files/8211199/1006139530.zip)

This is the file I noticed it on, a .wem in Astral Chain's sound folder. Probably not the best example but I don't know of any other, since it seems most files do have the loop point at the end of the file.

If you can't figure out how to build this feature into LAC, it'd appreciate if you could at least find a faster way to check if a file has an end-loop point before the end of a file. Thanks for your work.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
