### ISSUE TITLE
When inputting loop points, they dont get applied

### ISSUE THREAD

**Issue by mkwiimaster7** [libertyernie/LoopingAudioConverter#72]
Im trying to put loop points on a WAV file that has 8 channels, but when i input the loop points and check the output file, it says isLooped: False and the loop points arent there

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
