### ISSUE TITLE
Version 3.0 does not work at all when built

### ISSUE THREAD

**Issue by Bonboon229** [libertyernie/LoopingAudioConverter#73]
Tried compiling from code. Program does load, but all converting of any audio of any type does not initiate.
In short, the program is completly broken.

**Comment by IsaacSchemm** [comment]
Do you see any errors in the Output tab in Visual Studio or in the console?

**Comment by Bonboon229** [comment]
No. The Conversion process simply does not occur when using the program
Example: wav->hca, wav->brstm, so on

**Comment by Bonboon229** [comment]
Building the program does work though without error.

**Comment by Bonboon229** [comment]
Edit: I figured something out. When the program folder is moved from the build directory, it stops working properly.
Also pitch shifting still breaks the conversion process. Until these problems are fixed, I'm sticking with version 2.5

**Comment by libertyernie** [comment]
Would you mind filing another GitHub issue for the pitch shifting bug? Might help me keep track of it.

**Comment by Bonboon229** [comment]
can do

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
