### ISSUE TITLE
Pitch shifting causes conversions to fail in all versions past 2.5

### ISSUE THREAD

**Issue by Bonboon229** [libertyernie/LoopingAudioConverter#74]
Simply put, if the pitch setting is messed with in any way, the conversion silently fails.
No errors show in any log.

**Comment by libertyernie** [comment]
This might be fixed now with the change to #69. Didn't realize it was you who opened that one, sorry :)

Let me know if it still doesn't work or if I broke something else in the process.

**Comment by Bonboon229** [comment]
I tried that fix. It did NOT fix it.

**Comment by Bonboon229** [comment]
Edit: Did a rebuild of it from this commit. It does not work when moved out of the build folder.
Also, Pitch shifting still breaks conversions.

**Comment by saiveeon** [comment]
i encounter this same issue, but only when exporting the loop segment. if export loop segment is not checked, pitch shifting works, otherwise it causes a silent fail like described here.

**Comment by Bonboon229** [comment]
I had export loop segment unchecked and it still silently failed for me

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
