### ISSUE TITLE
[Request] Add a checkbox to "Apply Mario Kart Wii Final Lap Effect" and another to "Create A Second BRSTM with Final Lap Effect applied"

### ISSUE THREAD

**Issue by SilverMK6** [libertyernie/LoopingAudioConverter#76]
I'm not too knowledgable about audio, but producing a similar result in audacity is done by changing:
Initial and Final Tempo Change (%): a value from 6 to 20% (10% recommended)
Initial and Final Pitch Shift -> (semitones) [-12 to 12]: 1

There's also a program called "Final Lap Stream Maker" [https://wiki.tockdom.com/wiki/Final_Lap_Stream_Maker](url) that applies the effect, but it's not open source to my knowledge.

**Comment by SilverMK6** [comment]
I'm not too knowledgable about audio, but producing a similar result in audacity is done by changing:
Initial and Final Tempo Change (%): a value from 6 to 20% (10% recommended)
Initial and Final Pitch Shift -> (semitones) [-12 to 12]: 1

There's also a program called "Final Lap Stream Maker" [https://wiki.tockdom.com/wiki/Final_Lap_Stream_Maker](url) that applies the effect, but it's not open source to my knowledge.

**Comment by omerien** [comment]
Close this since it's now resolved

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
