### ISSUE TITLE
windows don't close after cancelling a conversion

### ISSUE THREAD

**Issue by CrossyChainsaw** [libertyernie/LoopingAudioConverter#78]
![image](https://user-images.githubusercontent.com/74303221/192362482-36ead712-5eeb-4c76-abce-d26ecb587531.png)

as you can see the windows don't close, this also brings another problem with it. while converting they won't load. You can also see that in the image.

**Comment by libertyernie** [comment]
Does the same issue occur on version 3.0?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
