### ISSUE TITLE
Conversion stuck on "Decoding" on every version

### ISSUE THREAD

**Issue by industdev** [libertyernie/LoopingAudioConverter#79]
No matter the option it doesn't convert to anything
![image](https://user-images.githubusercontent.com/66631504/193465860-597c573d-c4cd-4219-9cc5-eed4b5452551.png)

**Comment by libertyernie** [comment]
Could you post a link to the input audio file you're trying to convert?

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
