### ISSUE TITLE
(Request) Capcom ADPCM 

### ISSUE THREAD

**Issue by AyanamiRei1** [libertyernie/LoopingAudioConverter#85]
I'm having a bit of trouble finding a way to encode sounds in Capcom ADPCM. While I found a tool that encodes them it it's not the correct header according to Foobar2000.

This is the correct header 
![image](https://user-images.githubusercontent.com/25233407/211767320-79c916a1-614f-44eb-a753-2ef188fbffc8.png)

Would it be possible to add encoding in the future? Or direct me to something that does? Thank you.

**Comment by libertyernie** [comment]
I'm not quite familiar enough with the details of ADPCM and its container(s) - this app relies on BrawlCrate and/or VGAudio to do that sort of thing. Do you know of any open source tool that can fix the header to the format you need? I'd probably be able to integrate it if someone's already figured out the format.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
