### ISSUE TITLE
[Request] Linux version

### ISSUE THREAD

**Issue by omerien** [libertyernie/LoopingAudioConverter#86]
More people than you think don't have access to a Windows computer, so it would really help us to compile a Linux version for these people
It seems to be possible according to [Microsoft](https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio/)
Thanks if you just try !

**Comment by libertyernie** [comment]
Have you tried running LoopingAudioConverter.exe through mono? I think it might work - if it does, you'll still need to edit the .config file to point to Linux versions of those apps insteaad of Windows ones, but that shouldn't be too hard.

.NET Core / .NET 5+ do not include WinForms on Linux so using those frameworks would require someone writing a new GUI for LoopingAudioConverter.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
