### ISSUE TITLE
Can't increase tempo of BRSTM file

### ISSUE THREAD

**Issue by synthgloom** [libertyernie/LoopingAudioConverter#87]
I downloaded a BRSTM from smashcustommusic.net, and tried to make a 1.5x sped up version with LoopingAudioConverter. I got this error (pictured in screenshot). I don't really know what's causing it, unfortunately.

![image](https://user-images.githubusercontent.com/55351855/227666947-1483a726-201f-4443-a18b-7befe3f3f17d.png)

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
