### ISSUE TITLE
GUI Appearance Could Be Refined

### ISSUE THREAD

**Issue by ghost** [libertyernie/LoopingAudioConverter#9]
I'm using Trisquel 7 (based on Ubuntu 14.04) ... When I run the app, the GUI looks less refined than on Windows. Please observe the following screenshot. Thank you for LAC. It's a very useful app!

![screenshot from 2017-06-07 21 43 48](https://user-images.githubusercontent.com/1891288/26908755-bc16e43a-4bca-11e7-9207-1592b0a5102d.png)

If there is a way for me to improve this, please advise.

Regards,

David

**Comment by libertyernie** [comment]
I don't think there's that much I can do to make a Windows Forms app look
better on Linux. Maybe I could rewrite parts of it in GTK+ but that would
be more of a "for fun" type of thing.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
